### PR TITLE
fix assign bug and made it faster

### PR DESCRIPTION
**Pull request by MikeRoetgers**
- Loads all issues at once instead of one HTTP call per repo
- Not only taheris is assigned to PRs

### CODE REVIEW

**Comment by MikeRoetgers** [comment]
@husio The diff is quite big because I switched to another Github endpoint. And the endpoint returns issues not only PRs, therefore I had to rename the entity ... etc.

**Comment by husio** [comment]
I still don't see where the bug was, but I can see it's working now

:+1:

**Comment by MikeRoetgers** [comment]
@piotr the bug was this line: https://github.com/optiopay/github-stale-pr-bot/pull/6/files#diff-7ddfb3e035b42cd70649cc33393fe32cR188
Old: L174 New: L188

**Comment by husio** [comment]
@MikeRoetgers I really don't get it how. It's an array, so iteration should work just fine. Why was it allways assigning the same user?

**Comment by MikeRoetgers** [comment]
@piotr you were saving a pointer to `member` in the ring structure. With every iteration `member` is overwritten with the next value from the `members` slice but the memory address stays the same. So first iteration the ring has satran, second iteration the ring has MikeRoetgers, MikeRoetgers, third iteration the ring has husio, husio, husio and so on.

**Comment by husio** [comment]
It all makes sense now. Thanks for explanation!

**Pull request merged**
